In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import model_selection
from sklearn.model_selection import KFold

__Decision tree: w/o any modification of missing data__

In [64]:
df = pd.read_csv('bank-data/bank-additional-full.csv')
bank_object_data = df.select_dtypes(include="object")
bank_object_data.info()

bank_non_object_data = df.select_dtypes(exclude="object")
print(bank_non_object_data.info())

label = LabelEncoder()
bank_object_data = bank_object_data.apply(label.fit_transform)

print(bank_object_data.head())

bank_final = pd.concat([bank_object_data, bank_non_object_data], axis = 1)
print(bank_final.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 11 columns):
job            41188 non-null object
marital        41188 non-null object
education      41188 non-null object
default        41188 non-null object
housing        41188 non-null object
loan           41188 non-null object
contact        41188 non-null object
month          41188 non-null object
day_of_week    41188 non-null object
poutcome       41188 non-null object
y              41188 non-null object
dtypes: object(11)
memory usage: 3.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 10 columns):
age               41188 non-null int64
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m       

__Decision tree: w/o any modification of missing data; k fold__

In [65]:
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

kfold = KFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0))
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 88.73%
Accuracy: 0.89 (+/- 0.01)


array([0.88492353, 0.88565186, 0.88638019, 0.88905074, 0.88565186,
       0.88225297, 0.89002185, 0.88905074, 0.89533754, 0.88440991])

In [67]:
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

kfold = KFold(n_splits=10)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0))
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
print(results_kfold)

Accuracy: 87.31%
Accuracy: 0.87 (+/- 0.21)
[0.95508619 0.94950231 0.94294732 0.92328235 0.93517844 0.92740957
 0.8519058  0.85894635 0.79043225 0.59664886]


In [98]:
df = pd.read_csv('bank-data/bank-additional-full.csv')
t1 = df.copy()
for i in t1.columns:
    if len(t1.columns) > 4:
        t1.drop([i], axis = 1, inplace = True)
for i in t1.index:
    if len(t1.index) > 10:
        t1.drop([i], inplace = True)
t1 = t1.set_index(np.arange(0,len(t1)))

In [100]:
t1

cons.conf.idx  euribor3m  nr.employed    y
0          -50.8      1.031       4963.6  yes
1          -50.8      1.028       4963.6   no
2          -50.8      1.028       4963.6   no
3          -50.8      1.028       4963.6  yes
4          -50.8      1.028       4963.6   no
5          -50.8      1.028       4963.6  yes
6          -50.8      1.028       4963.6   no
7          -50.8      1.028       4963.6   no
8          -50.8      1.028       4963.6  yes
9          -50.8      1.028       4963.6   no

In [101]:
X = t1.drop(['y'], axis = 1)
Y = t1['y']
kf = KFold(n_splits=5)
kf.split(t1) 
for train_index, test_index in kf.split(t1):
    #X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]
    print(train_index, test_index)
    #print(X_train,y_train)
    #print(X_test,y_test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [102]:
X = t1.drop(['y'], axis = 1)
Y = t1['y']
kf = KFold(n_splits=5, random_state=100, shuffle = True)
kf.split(t1) 
for train_index, test_index in kf.split(t1):
    #X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]
    print(train_index, test_index)
    #print(X_train,y_train)
    #print(X_test,y_test)

[0 1 2 3 4 5 8 9] [6 7]
[0 2 3 4 6 7 8 9] [1 5]
[0 1 3 5 6 7 8 9] [2 4]
[1 2 4 5 6 7 8 9] [0 3]
[0 1 2 3 4 5 6 7] [8 9]


In [106]:
X = t1.drop(['y'], axis = 1)
Y = t1['y']
kf = KFold(n_splits=5, random_state=0, shuffle = True)
kf.split(X,Y) 
for train_index, test_index in kf.split(X):
    #X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]
    print(train_index, test_index)
    #print(X_train,y_train)
    #print(X_test,y_test)
for train_index, test_index in kf.split(Y):
    #X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]
    print(train_index, test_index)
    #print(X_train,y_train)
    #print(X_test,y_test)

[0 1 3 4 5 6 7 9] [2 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 2 3 4 5 7 8 9] [1 6]
[0 1 2 4 5 6 8 9] [3 7]
[1 2 3 4 6 7 8 9] [0 5]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 2 3 4 5 7 8 9] [1 6]
[0 1 2 4 5 6 8 9] [3 7]
[1 2 3 4 6 7 8 9] [0 5]


In [112]:
X = t1.drop(['y'], axis = 1)
Y = t1['y']
skf = StratifiedKFold(n_splits=5, random_state=100, shuffle = True)
skf.split(X, Y) 
for train_index in skf.split(X,Y):
    #X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    #y_train, y_test = Y[train_index], Y[test_index]
    print(train_index)
    #print(X_train,y_train)
    #print(X_test,y_test)

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))
(array([0, 2, 4, 5, 6, 7, 8, 9]), array([1, 3]))
(array([1, 2, 3, 4, 5, 6, 8, 9]), array([0, 7]))
(array([0, 1, 3, 4, 6, 7, 8, 9]), array([2, 5]))
(array([0, 1, 2, 3, 5, 7, 8, 9]), array([4, 6]))


C:\Python3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


In [74]:

clf = DecisionTreeClassifier(random_state=20)
kf = KFold(n_splits=10, random_state=100, shuffle = True)
kf.split(bank_final) 
for train_index, test_index in kf.split(bank_final):
    print(train_index, test_index)

[    0     1     2 ... 41185 41186 41187] [    7     8    12 ... 41174 41178 41183]
[    0     1     2 ... 41185 41186 41187] [   19    24    52 ... 41167 41169 41184]
[    0     1     2 ... 41185 41186 41187] [   31    36    38 ... 41152 41156 41162]
[    0     1     3 ... 41184 41185 41186] [    2     5     6 ... 41159 41164 41187]
[    0     1     2 ... 41184 41186 41187] [    3     4    11 ... 41170 41180 41185]
[    0     1     2 ... 41184 41185 41187] [   13    21    41 ... 41168 41173 41186]
[    0     2     3 ... 41185 41186 41187] [    1    10    15 ... 41175 41177 41181]
[    1     2     3 ... 41185 41186 41187] [    0    14    18 ... 41155 41172 41179]
[    0     1     2 ... 41185 41186 41187] [   27    48    62 ... 41143 41144 41182]
[    0     1     2 ... 41185 41186 41187] [    9    28    40 ... 41154 41171 41176]


In [71]:
clf = DecisionTreeClassifier(random_state=20)
kf = KFold(n_splits=10, random_state=100, shuffle = True)
kf.split(X,Y) 
# Initialize the accuracy of the models to blank list. The accuracy of each model will be appended to this list
accuracy_model = []

# Iterate over each train-test split
for train_index, test_index in kf.split(X):
    # Split train-test
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    # Train the model
    model = clf.fit(X_train, y_train)
    # Append to accuracy_model the accuracy of the model
    accuracy_model.append(accuracy_score(y_test, model.predict(X_test), normalize=True)*100)
 
# Print the accuracy    
print(accuracy_model)


[88.49235251274581, 88.56518572469045, 88.6380189366351, 88.90507404709881, 88.56518572469045, 88.22529740228211, 89.00218499635834, 88.90507404709881, 89.53375424963575, 88.44099077221952]


In [72]:
import statistics
print(statistics.mean(accuracy_model))
print(statistics.stdev(accuracy_model))

88.72731184134551
0.37101220836588134


__Decision tree: w/o any modification of missing data; stratified k fold__

In [40]:
from sklearn.model_selection import StratifiedKFold
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

skfold = StratifiedKFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=skfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0)) 
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 88.80%
Accuracy: 0.89 (+/- 0.00)


array([0.8926924 , 0.88589463, 0.88759408, 0.88807963, 0.8873513 ,
       0.89026463, 0.88565186, 0.88783685, 0.8863526 , 0.88878096])

__Decision tree: deleting missing data__

In [2]:
df = pd.read_csv('bank-data/bank-additional-full.csv')
print(df.shape)
print(df.columns)
print((df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']] == 'unknown').sum())

df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']] = df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']].replace('unknown', np.NaN)
print(df.isnull().sum())

df.dropna(inplace=True)
# summarize the number of rows and columns in the dataset
print(df.shape)

NameError: name 'pd' is not defined

In [1]:
bank_object_data = df.select_dtypes(include="object")
print(bank_object_data.info())

bank_non_object_data = df.select_dtypes(exclude="object")
print(bank_non_object_data.info())

label = LabelEncoder()
bank_object_data = bank_object_data.apply(label.fit_transform)

print(bank_object_data.head())

bank_final = pd.concat([bank_object_data, bank_non_object_data], axis = 1)

print(bank_final.head())

NameError: name 'df' is not defined

In [50]:
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

kfold = KFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0)) 
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 87.84%
Accuracy: 0.88 (+/- 0.01)


array([0.89078386, 0.87569695, 0.87602493, 0.8806166 , 0.87700886,
       0.88291243, 0.87536897, 0.8806166 , 0.87467192, 0.87040682])

__Decision Tree: deleting missing data; stratified k fold__

In [51]:
from sklearn.model_selection import StratifiedKFold
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

skfold = StratifiedKFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=skfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0)) 
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 87.83%
Accuracy: 0.88 (+/- 0.01)


array([0.8806166 , 0.87963267, 0.88094457, 0.87602493, 0.87012135,
       0.87668088, 0.88717612, 0.87602493, 0.87828084, 0.87729659])

__Decision Tree: with imputation__

In [2]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

df = pd.read_csv('bank-data/bank-additional-full.csv')
print(df.shape)
print(df.columns)
print((df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']] == 'unknown').sum())

df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']] = df[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']].replace('unknown', np.NaN)
print(df.isnull().sum())

(41188, 21)
Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')


C:\Python3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64
age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64


In [3]:
bank_object_data = df.select_dtypes(include="object")
print(bank_object_data.info())

bank_non_object_data = df.select_dtypes(exclude="object")
print(bank_non_object_data.info())

values = bank_non_object_data.values
#imputer = Imputer()
transformed_values = imputer.fit_transform(values)
# count the number of NaN values in each column
print(np.isnan(transformed_values).sum())
print(np.isnan(bank_non_object_data.values).sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 11 columns):
job            40858 non-null object
marital        41108 non-null object
education      39457 non-null object
default        32591 non-null object
housing        40198 non-null object
loan           40198 non-null object
contact        41188 non-null object
month          41188 non-null object
day_of_week    41188 non-null object
poutcome       41188 non-null object
y              41188 non-null object
dtypes: object(11)
memory usage: 3.5+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 10 columns):
age               41188 non-null int64
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m  

In [4]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)


bank_object_data = DataFrameImputer().fit_transform(bank_object_data)

In [5]:
label = LabelEncoder()
bank_object_data = bank_object_data.apply(label.fit_transform)

print(bank_object_data.head())

bank_final = pd.concat([bank_object_data, bank_non_object_data], axis = 1)

print(bank_final.head())

   job  marital  education  default  housing  loan  contact  month  \
0    3        1          0        0        0     0        1      6   
1    7        1          3        0        0     0        1      6   
2    7        1          3        0        1     0        1      6   
3    0        1          1        0        0     0        1      6   
4    7        1          3        0        0     1        1      6   

   day_of_week  poutcome  y  
0            1         1  0  
1            1         1  0  
2            1         1  0  
3            1         1  0  
4            1         1  0  
   job  marital  education  default  housing  loan  contact  month  \
0    3        1          0        0        0     0        1      6   
1    7        1          3        0        0     0        1      6   
2    7        1          3        0        1     0        1      6   
3    0        1          1        0        0     0        1      6   
4    7        1          3        0        0     

__Decision Tree: with imputation; k fold__

In [21]:
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

kfold = KFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0)) 
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 88.87%
Accuracy: 0.89 (+/- 0.01)


array([0.88662297, 0.88832241, 0.88662297, 0.89099296, 0.88759408,
       0.88346686, 0.89414907, 0.8895363 , 0.89290918, 0.88659543])

__Decision Tree: with imputation; stratified k fold__

In [62]:
from sklearn.model_selection import StratifiedKFold
X = bank_final.drop(['y'], axis = 1)
Y = bank_final['y']

model = DecisionTreeClassifier(random_state=20)

skfold = StratifiedKFold(n_splits=10, random_state=100, shuffle = True)
results_kfold = model_selection.cross_val_score(model, X, Y, cv=skfold)
print("Accuracy: %.2f%%" % (results_kfold.mean()*100.0)) 
print("Accuracy: %0.2f (+/- %0.2f)" % (results_kfold.mean(), results_kfold.std() * 2))
results_kfold

Accuracy: 88.82%
Accuracy: 0.89 (+/- 0.00)


array([0.88468075, 0.89172129, 0.88783685, 0.88905074, 0.89099296,
       0.88710852, 0.88419519, 0.89075018, 0.88829529, 0.88756678])